branches:
  - main

plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits

  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      presetConfig:
        types:
          - type: feat
            section: "âœ¨ Features"
            hidden: false
          - type: fix
            section: "ðŸ› Bug Fixes"
            hidden: false
          - type: perf
            section: "ðŸš€ Performance Improvements"
            hidden: false
          - type: revert
            section: "âª Reverts"
            hidden: false
          - type: docs
            section: "ðŸ“ Documentation"
            hidden: false
          - type: style
            section: "ðŸ’„ Styles"
            hidden: true
          - type: chore
            section: "ðŸ§¹ Miscellaneous Chores"
            hidden: true
          - type: refactor
            section: "ðŸ”¨ Code Refactoring"
            hidden: false
          - type: test
            section: "ðŸ§ª Tests"
            hidden: true
          - type: build
            section: "ðŸ“¦ Build System"
            hidden: true
          - type: ci
            section: "ðŸ¤– Continuous Integration"
            hidden: true

  - - "@semantic-release/changelog"
    - changelogFile: "CHANGELOG.md"

  - - "semantic-release-vsce"
    - packageVsix: true
      publish: true

  - - "@semantic-release/git"
    - assets:
        - package.json
        - package-lock.json
        - CHANGELOG.md
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"

  - - "@semantic-release/github"
    - assets:
        - label: "Extension VSIX"
          path: "*.vsix"
      draft: true

  - - "@semantic-release/exec"
    - successCmd: 'echo "new_release_published=true" >> $GITHUB_OUTPUT'
